package by.training.hrsystem.controller;

public enum CommandName {
	USER_LOGIN, USER_REGISTRARION, USER_LOGOUT, SWITCH_LOCALE, TO_PRIVATE_OFFICE, TO_REGISTRATION_PAGE,
	TO_INDEX_PAGE, TO_APPLICANT_EDIT_PROFILE, APPLICANT_EDIT_PROFILE, ADD_RESUME,
	TO_APPLICANT_ADD_RESUME, TO_APPLICANT_LIST_RESUME, TO_APPLICANT_PROFILE, SHOW_VACANCY,TO_HR_LIST_VACANCY,
	TO_HR_ADD_VACANCY_PAGE, ADD_VACANCY, HR_PRIVATE_OFFICE_SHOW_VACANCY,DELETE_VACANCY,ACTIVATE_VACANCY,DEACTIVATE_VACANCY,
	HOT_VACANCY, TO_APPLICANT_EDIT_RESUME, SHOW_RESUME, EDIT_RESUME,ADD_EDUCATION;

}
