package by.training.hrsystem.controller;

public enum CommandName {
	USER_LOGIN, USER_REGISTRARION, USER_LOGOUT, SWITCH_LOCALE, TO_PRIVATE_OFFICE, TO_REGISTRATION_PAGE, TO_INDEX_PAGE, TO_APPLICANT_EDIT_PROFILE, APPLICANT_EDIT_PROFILE, ADD_RESUME,
	TO_APPLICANT_ADD_RESUME, TO_APPLICANT_LIST_RESUME, TO_APPLICANT_PROFILE;

}
