package by.training.hrsystem.controller;

public enum CommandName {
	USER_LOGIN, USER_REGISTRARION, USER_LOGOUT, SWITCH_LOCALE, TO_PRIVATE_OFFICE, TO_REGISTRATION_PAGE,
	TO_INDEX_PAGE, TO_APPLICANT_EDIT_PROFILE, APPLICANT_EDIT_PROFILE, ADD_RESUME,
	TO_APPLICANT_ADD_RESUME, TO_APPLICANT_LIST_RESUME, TO_APPLICANT_PROFILE, SHOW_VACANCY,TO_HR_LIST_VACANCY,
	TO_HR_ADD_VACANCY_PAGE, ADD_VACANCY, HR_PRIVATE_OFFICE_SHOW_VACANCY,DELETE_VACANCY,ACTIVATE_VACANCY,DEACTIVATE_VACANCY,
	HOT_VACANCY, TO_APPLICANT_EDIT_RESUME, SHOW_RESUME, EDIT_RESUME, ADD_EDUCATION, DELETE_EDUCATION, EDIT_EDUCATION,
	ADD_RESUME_LANGUAGE,EDIT_RESUME_LANGUAGE,DELETE_RESUME_LANGUAGE,ADD_SKILL,DELETE_SKILL,EDIT_SKILL,
	ADD_WORKPLACE,EDIT_WORKPLACE,DELETE_WORKPLACE,SEARCH_VACANCY,ADD_RESUME_TO_VACANCY,TO_VERIFY_LIST,
	SHOW_APPLICANT_WHO_LEAVE_RESUME;

}
